### PR TITLE
Adds `withUpdate` to widget.js

### PR DESCRIPTION
**Pull request by NicolasPetton**
This adds a transaction-like update to widgets.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
If that's fine with everybody, I'll just merge this one :ship:

**Comment by whenrik** [comment]
Looks nice but will it solve the problem? Don't we need to be more explicit with when the update is done?

We usually have a widget with a public API where each method do something and then update. It would be nice if the calling code could decide to create a transaction. Eg.

~~~~

tableWidget.preventUpdate();
tableWidget.addRow(firstRow);
tableWidget.addRow(secondRow);
tableWidget.update();
~~~~

or would this do it?

~~~~

tableWidget.withUpdate(function() {
  tableWidget.addRow(firstRow);
  tableWidget.addRow(secondRow);
});

~~~~

sometimes we have multiple widgets and want to update them withing one transaction

**Comment by NicolasPetton** [comment]
It will work, but only within one widget.

In a second step, we could extract an updateTransaction object, so that several widgets could update using the same transaction, so that you only perform the update once, for several widgets.

**Comment by whenrik** [comment]
:+1: Lets merge this one

**Pull request merged**
